
namespace Employees_Management_System.User_Controls
{
    partial class Employees
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Employees));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.btnBlacklist = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEmployeeQRCardInfo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEmployeeEditing = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEmployeeAccount = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEmployeeRegistration = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // btnBlacklist
            // 
            this.btnBlacklist.AllowAnimations = true;
            this.btnBlacklist.AllowMouseEffects = true;
            this.btnBlacklist.AllowToggling = false;
            this.btnBlacklist.AnimationSpeed = 200;
            this.btnBlacklist.AutoGenerateColors = false;
            this.btnBlacklist.AutoRoundBorders = false;
            this.btnBlacklist.AutoSizeLeftIcon = true;
            this.btnBlacklist.AutoSizeRightIcon = true;
            this.btnBlacklist.BackColor = System.Drawing.Color.Transparent;
            this.btnBlacklist.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBlacklist.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBlacklist.BackgroundImage")));
            this.btnBlacklist.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBlacklist.ButtonText = "დამატება";
            this.btnBlacklist.ButtonTextMarginLeft = 0;
            this.btnBlacklist.ColorContrastOnClick = 45;
            this.btnBlacklist.ColorContrastOnHover = 45;
            this.btnBlacklist.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnBlacklist.CustomizableEdges = borderEdges1;
            this.btnBlacklist.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBlacklist.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBlacklist.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBlacklist.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBlacklist.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBlacklist.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBlacklist.ForeColor = System.Drawing.Color.White;
            this.btnBlacklist.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBlacklist.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBlacklist.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBlacklist.IconMarginLeft = 11;
            this.btnBlacklist.IconPadding = 10;
            this.btnBlacklist.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBlacklist.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBlacklist.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBlacklist.IconSize = 25;
            this.btnBlacklist.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBlacklist.IdleBorderRadius = 20;
            this.btnBlacklist.IdleBorderThickness = 1;
            this.btnBlacklist.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBlacklist.IdleIconLeftImage = null;
            this.btnBlacklist.IdleIconRightImage = null;
            this.btnBlacklist.IndicateFocus = false;
            this.btnBlacklist.Location = new System.Drawing.Point(921, 655);
            this.btnBlacklist.Name = "btnBlacklist";
            this.btnBlacklist.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBlacklist.OnDisabledState.BorderRadius = 20;
            this.btnBlacklist.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBlacklist.OnDisabledState.BorderThickness = 1;
            this.btnBlacklist.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBlacklist.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBlacklist.OnDisabledState.IconLeftImage = null;
            this.btnBlacklist.OnDisabledState.IconRightImage = null;
            this.btnBlacklist.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBlacklist.onHoverState.BorderRadius = 20;
            this.btnBlacklist.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBlacklist.onHoverState.BorderThickness = 1;
            this.btnBlacklist.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBlacklist.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBlacklist.onHoverState.IconLeftImage = null;
            this.btnBlacklist.onHoverState.IconRightImage = null;
            this.btnBlacklist.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBlacklist.OnIdleState.BorderRadius = 20;
            this.btnBlacklist.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBlacklist.OnIdleState.BorderThickness = 1;
            this.btnBlacklist.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBlacklist.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBlacklist.OnIdleState.IconLeftImage = null;
            this.btnBlacklist.OnIdleState.IconRightImage = null;
            this.btnBlacklist.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBlacklist.OnPressedState.BorderRadius = 20;
            this.btnBlacklist.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBlacklist.OnPressedState.BorderThickness = 1;
            this.btnBlacklist.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBlacklist.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBlacklist.OnPressedState.IconLeftImage = null;
            this.btnBlacklist.OnPressedState.IconRightImage = null;
            this.btnBlacklist.Size = new System.Drawing.Size(200, 39);
            this.btnBlacklist.TabIndex = 11;
            this.btnBlacklist.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBlacklist.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBlacklist.TextMarginLeft = 0;
            this.btnBlacklist.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBlacklist.UseDefaultRadiusAndThickness = true;
            this.btnBlacklist.Click += new System.EventHandler(this.btnBlacklist_Click);
            // 
            // btnEmployeeQRCardInfo
            // 
            this.btnEmployeeQRCardInfo.AllowAnimations = true;
            this.btnEmployeeQRCardInfo.AllowMouseEffects = true;
            this.btnEmployeeQRCardInfo.AllowToggling = false;
            this.btnEmployeeQRCardInfo.AnimationSpeed = 200;
            this.btnEmployeeQRCardInfo.AutoGenerateColors = false;
            this.btnEmployeeQRCardInfo.AutoRoundBorders = false;
            this.btnEmployeeQRCardInfo.AutoSizeLeftIcon = true;
            this.btnEmployeeQRCardInfo.AutoSizeRightIcon = true;
            this.btnEmployeeQRCardInfo.BackColor = System.Drawing.Color.Transparent;
            this.btnEmployeeQRCardInfo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeQRCardInfo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEmployeeQRCardInfo.BackgroundImage")));
            this.btnEmployeeQRCardInfo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeQRCardInfo.ButtonText = "ინფორმაცია";
            this.btnEmployeeQRCardInfo.ButtonTextMarginLeft = 0;
            this.btnEmployeeQRCardInfo.ColorContrastOnClick = 45;
            this.btnEmployeeQRCardInfo.ColorContrastOnHover = 45;
            this.btnEmployeeQRCardInfo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnEmployeeQRCardInfo.CustomizableEdges = borderEdges2;
            this.btnEmployeeQRCardInfo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEmployeeQRCardInfo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployeeQRCardInfo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployeeQRCardInfo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployeeQRCardInfo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEmployeeQRCardInfo.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmployeeQRCardInfo.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeQRCardInfo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEmployeeQRCardInfo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployeeQRCardInfo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEmployeeQRCardInfo.IconMarginLeft = 11;
            this.btnEmployeeQRCardInfo.IconPadding = 10;
            this.btnEmployeeQRCardInfo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEmployeeQRCardInfo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployeeQRCardInfo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEmployeeQRCardInfo.IconSize = 25;
            this.btnEmployeeQRCardInfo.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeQRCardInfo.IdleBorderRadius = 20;
            this.btnEmployeeQRCardInfo.IdleBorderThickness = 1;
            this.btnEmployeeQRCardInfo.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeQRCardInfo.IdleIconLeftImage = null;
            this.btnEmployeeQRCardInfo.IdleIconRightImage = null;
            this.btnEmployeeQRCardInfo.IndicateFocus = false;
            this.btnEmployeeQRCardInfo.Location = new System.Drawing.Point(497, 655);
            this.btnEmployeeQRCardInfo.Name = "btnEmployeeQRCardInfo";
            this.btnEmployeeQRCardInfo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployeeQRCardInfo.OnDisabledState.BorderRadius = 20;
            this.btnEmployeeQRCardInfo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeQRCardInfo.OnDisabledState.BorderThickness = 1;
            this.btnEmployeeQRCardInfo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployeeQRCardInfo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployeeQRCardInfo.OnDisabledState.IconLeftImage = null;
            this.btnEmployeeQRCardInfo.OnDisabledState.IconRightImage = null;
            this.btnEmployeeQRCardInfo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEmployeeQRCardInfo.onHoverState.BorderRadius = 20;
            this.btnEmployeeQRCardInfo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeQRCardInfo.onHoverState.BorderThickness = 1;
            this.btnEmployeeQRCardInfo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEmployeeQRCardInfo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeQRCardInfo.onHoverState.IconLeftImage = null;
            this.btnEmployeeQRCardInfo.onHoverState.IconRightImage = null;
            this.btnEmployeeQRCardInfo.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeQRCardInfo.OnIdleState.BorderRadius = 20;
            this.btnEmployeeQRCardInfo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeQRCardInfo.OnIdleState.BorderThickness = 1;
            this.btnEmployeeQRCardInfo.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeQRCardInfo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeQRCardInfo.OnIdleState.IconLeftImage = null;
            this.btnEmployeeQRCardInfo.OnIdleState.IconRightImage = null;
            this.btnEmployeeQRCardInfo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeQRCardInfo.OnPressedState.BorderRadius = 20;
            this.btnEmployeeQRCardInfo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeQRCardInfo.OnPressedState.BorderThickness = 1;
            this.btnEmployeeQRCardInfo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeQRCardInfo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeQRCardInfo.OnPressedState.IconLeftImage = null;
            this.btnEmployeeQRCardInfo.OnPressedState.IconRightImage = null;
            this.btnEmployeeQRCardInfo.Size = new System.Drawing.Size(200, 39);
            this.btnEmployeeQRCardInfo.TabIndex = 10;
            this.btnEmployeeQRCardInfo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmployeeQRCardInfo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEmployeeQRCardInfo.TextMarginLeft = 0;
            this.btnEmployeeQRCardInfo.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEmployeeQRCardInfo.UseDefaultRadiusAndThickness = true;
            this.btnEmployeeQRCardInfo.Click += new System.EventHandler(this.btnEmployeeQRCardInfo_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "ინფორმაცია";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges3;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.IdleBorderRadius = 20;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(921, 294);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 20;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 20;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnIdleState.BorderRadius = 20;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 20;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(200, 39);
            this.bunifuButton3.TabIndex = 9;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            // 
            // btnEmployeeEditing
            // 
            this.btnEmployeeEditing.AllowAnimations = true;
            this.btnEmployeeEditing.AllowMouseEffects = true;
            this.btnEmployeeEditing.AllowToggling = false;
            this.btnEmployeeEditing.AnimationSpeed = 200;
            this.btnEmployeeEditing.AutoGenerateColors = false;
            this.btnEmployeeEditing.AutoRoundBorders = false;
            this.btnEmployeeEditing.AutoSizeLeftIcon = true;
            this.btnEmployeeEditing.AutoSizeRightIcon = true;
            this.btnEmployeeEditing.BackColor = System.Drawing.Color.Transparent;
            this.btnEmployeeEditing.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeEditing.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEmployeeEditing.BackgroundImage")));
            this.btnEmployeeEditing.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeEditing.ButtonText = "რედაქტირება";
            this.btnEmployeeEditing.ButtonTextMarginLeft = 0;
            this.btnEmployeeEditing.ColorContrastOnClick = 45;
            this.btnEmployeeEditing.ColorContrastOnHover = 45;
            this.btnEmployeeEditing.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnEmployeeEditing.CustomizableEdges = borderEdges4;
            this.btnEmployeeEditing.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEmployeeEditing.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployeeEditing.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployeeEditing.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployeeEditing.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEmployeeEditing.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmployeeEditing.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeEditing.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEmployeeEditing.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployeeEditing.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEmployeeEditing.IconMarginLeft = 11;
            this.btnEmployeeEditing.IconPadding = 10;
            this.btnEmployeeEditing.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEmployeeEditing.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployeeEditing.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEmployeeEditing.IconSize = 25;
            this.btnEmployeeEditing.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeEditing.IdleBorderRadius = 20;
            this.btnEmployeeEditing.IdleBorderThickness = 1;
            this.btnEmployeeEditing.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeEditing.IdleIconLeftImage = null;
            this.btnEmployeeEditing.IdleIconRightImage = null;
            this.btnEmployeeEditing.IndicateFocus = false;
            this.btnEmployeeEditing.Location = new System.Drawing.Point(497, 294);
            this.btnEmployeeEditing.Name = "btnEmployeeEditing";
            this.btnEmployeeEditing.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployeeEditing.OnDisabledState.BorderRadius = 20;
            this.btnEmployeeEditing.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeEditing.OnDisabledState.BorderThickness = 1;
            this.btnEmployeeEditing.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployeeEditing.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployeeEditing.OnDisabledState.IconLeftImage = null;
            this.btnEmployeeEditing.OnDisabledState.IconRightImage = null;
            this.btnEmployeeEditing.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEmployeeEditing.onHoverState.BorderRadius = 20;
            this.btnEmployeeEditing.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeEditing.onHoverState.BorderThickness = 1;
            this.btnEmployeeEditing.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEmployeeEditing.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeEditing.onHoverState.IconLeftImage = null;
            this.btnEmployeeEditing.onHoverState.IconRightImage = null;
            this.btnEmployeeEditing.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeEditing.OnIdleState.BorderRadius = 20;
            this.btnEmployeeEditing.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeEditing.OnIdleState.BorderThickness = 1;
            this.btnEmployeeEditing.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeEditing.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeEditing.OnIdleState.IconLeftImage = null;
            this.btnEmployeeEditing.OnIdleState.IconRightImage = null;
            this.btnEmployeeEditing.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeEditing.OnPressedState.BorderRadius = 20;
            this.btnEmployeeEditing.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeEditing.OnPressedState.BorderThickness = 1;
            this.btnEmployeeEditing.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeEditing.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeEditing.OnPressedState.IconLeftImage = null;
            this.btnEmployeeEditing.OnPressedState.IconRightImage = null;
            this.btnEmployeeEditing.Size = new System.Drawing.Size(200, 39);
            this.btnEmployeeEditing.TabIndex = 8;
            this.btnEmployeeEditing.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmployeeEditing.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEmployeeEditing.TextMarginLeft = 0;
            this.btnEmployeeEditing.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEmployeeEditing.UseDefaultRadiusAndThickness = true;
            this.btnEmployeeEditing.Click += new System.EventHandler(this.btnEmployeeEditing_Click);
            // 
            // btnEmployeeAccount
            // 
            this.btnEmployeeAccount.AllowAnimations = true;
            this.btnEmployeeAccount.AllowMouseEffects = true;
            this.btnEmployeeAccount.AllowToggling = false;
            this.btnEmployeeAccount.AnimationSpeed = 200;
            this.btnEmployeeAccount.AutoGenerateColors = false;
            this.btnEmployeeAccount.AutoRoundBorders = false;
            this.btnEmployeeAccount.AutoSizeLeftIcon = true;
            this.btnEmployeeAccount.AutoSizeRightIcon = true;
            this.btnEmployeeAccount.BackColor = System.Drawing.Color.Transparent;
            this.btnEmployeeAccount.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeAccount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEmployeeAccount.BackgroundImage")));
            this.btnEmployeeAccount.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeAccount.ButtonText = "შექმნა";
            this.btnEmployeeAccount.ButtonTextMarginLeft = 0;
            this.btnEmployeeAccount.ColorContrastOnClick = 45;
            this.btnEmployeeAccount.ColorContrastOnHover = 45;
            this.btnEmployeeAccount.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnEmployeeAccount.CustomizableEdges = borderEdges5;
            this.btnEmployeeAccount.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEmployeeAccount.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployeeAccount.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployeeAccount.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployeeAccount.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEmployeeAccount.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmployeeAccount.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeAccount.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEmployeeAccount.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployeeAccount.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEmployeeAccount.IconMarginLeft = 11;
            this.btnEmployeeAccount.IconPadding = 10;
            this.btnEmployeeAccount.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEmployeeAccount.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployeeAccount.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEmployeeAccount.IconSize = 25;
            this.btnEmployeeAccount.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeAccount.IdleBorderRadius = 20;
            this.btnEmployeeAccount.IdleBorderThickness = 1;
            this.btnEmployeeAccount.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeAccount.IdleIconLeftImage = null;
            this.btnEmployeeAccount.IdleIconRightImage = null;
            this.btnEmployeeAccount.IndicateFocus = false;
            this.btnEmployeeAccount.Location = new System.Drawing.Point(75, 655);
            this.btnEmployeeAccount.Name = "btnEmployeeAccount";
            this.btnEmployeeAccount.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployeeAccount.OnDisabledState.BorderRadius = 20;
            this.btnEmployeeAccount.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeAccount.OnDisabledState.BorderThickness = 1;
            this.btnEmployeeAccount.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployeeAccount.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployeeAccount.OnDisabledState.IconLeftImage = null;
            this.btnEmployeeAccount.OnDisabledState.IconRightImage = null;
            this.btnEmployeeAccount.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEmployeeAccount.onHoverState.BorderRadius = 20;
            this.btnEmployeeAccount.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeAccount.onHoverState.BorderThickness = 1;
            this.btnEmployeeAccount.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEmployeeAccount.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeAccount.onHoverState.IconLeftImage = null;
            this.btnEmployeeAccount.onHoverState.IconRightImage = null;
            this.btnEmployeeAccount.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeAccount.OnIdleState.BorderRadius = 20;
            this.btnEmployeeAccount.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeAccount.OnIdleState.BorderThickness = 1;
            this.btnEmployeeAccount.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeAccount.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeAccount.OnIdleState.IconLeftImage = null;
            this.btnEmployeeAccount.OnIdleState.IconRightImage = null;
            this.btnEmployeeAccount.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeAccount.OnPressedState.BorderRadius = 20;
            this.btnEmployeeAccount.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeAccount.OnPressedState.BorderThickness = 1;
            this.btnEmployeeAccount.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeAccount.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeAccount.OnPressedState.IconLeftImage = null;
            this.btnEmployeeAccount.OnPressedState.IconRightImage = null;
            this.btnEmployeeAccount.Size = new System.Drawing.Size(200, 39);
            this.btnEmployeeAccount.TabIndex = 7;
            this.btnEmployeeAccount.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmployeeAccount.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEmployeeAccount.TextMarginLeft = 0;
            this.btnEmployeeAccount.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEmployeeAccount.UseDefaultRadiusAndThickness = true;
            this.btnEmployeeAccount.Click += new System.EventHandler(this.btnEmployeeAccount_Click);
            // 
            // btnEmployeeRegistration
            // 
            this.btnEmployeeRegistration.AllowAnimations = true;
            this.btnEmployeeRegistration.AllowMouseEffects = true;
            this.btnEmployeeRegistration.AllowToggling = false;
            this.btnEmployeeRegistration.AnimationSpeed = 200;
            this.btnEmployeeRegistration.AutoGenerateColors = false;
            this.btnEmployeeRegistration.AutoRoundBorders = false;
            this.btnEmployeeRegistration.AutoSizeLeftIcon = true;
            this.btnEmployeeRegistration.AutoSizeRightIcon = true;
            this.btnEmployeeRegistration.BackColor = System.Drawing.Color.Transparent;
            this.btnEmployeeRegistration.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeRegistration.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEmployeeRegistration.BackgroundImage")));
            this.btnEmployeeRegistration.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeRegistration.ButtonText = "რეგისტრაცია";
            this.btnEmployeeRegistration.ButtonTextMarginLeft = 0;
            this.btnEmployeeRegistration.ColorContrastOnClick = 45;
            this.btnEmployeeRegistration.ColorContrastOnHover = 45;
            this.btnEmployeeRegistration.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnEmployeeRegistration.CustomizableEdges = borderEdges6;
            this.btnEmployeeRegistration.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEmployeeRegistration.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployeeRegistration.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployeeRegistration.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployeeRegistration.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEmployeeRegistration.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmployeeRegistration.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeRegistration.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEmployeeRegistration.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployeeRegistration.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEmployeeRegistration.IconMarginLeft = 11;
            this.btnEmployeeRegistration.IconPadding = 10;
            this.btnEmployeeRegistration.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEmployeeRegistration.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployeeRegistration.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEmployeeRegistration.IconSize = 25;
            this.btnEmployeeRegistration.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeRegistration.IdleBorderRadius = 20;
            this.btnEmployeeRegistration.IdleBorderThickness = 1;
            this.btnEmployeeRegistration.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeRegistration.IdleIconLeftImage = null;
            this.btnEmployeeRegistration.IdleIconRightImage = null;
            this.btnEmployeeRegistration.IndicateFocus = false;
            this.btnEmployeeRegistration.Location = new System.Drawing.Point(75, 294);
            this.btnEmployeeRegistration.Name = "btnEmployeeRegistration";
            this.btnEmployeeRegistration.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployeeRegistration.OnDisabledState.BorderRadius = 20;
            this.btnEmployeeRegistration.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeRegistration.OnDisabledState.BorderThickness = 1;
            this.btnEmployeeRegistration.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployeeRegistration.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployeeRegistration.OnDisabledState.IconLeftImage = null;
            this.btnEmployeeRegistration.OnDisabledState.IconRightImage = null;
            this.btnEmployeeRegistration.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEmployeeRegistration.onHoverState.BorderRadius = 20;
            this.btnEmployeeRegistration.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeRegistration.onHoverState.BorderThickness = 1;
            this.btnEmployeeRegistration.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEmployeeRegistration.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeRegistration.onHoverState.IconLeftImage = null;
            this.btnEmployeeRegistration.onHoverState.IconRightImage = null;
            this.btnEmployeeRegistration.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeRegistration.OnIdleState.BorderRadius = 20;
            this.btnEmployeeRegistration.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeRegistration.OnIdleState.BorderThickness = 1;
            this.btnEmployeeRegistration.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeRegistration.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeRegistration.OnIdleState.IconLeftImage = null;
            this.btnEmployeeRegistration.OnIdleState.IconRightImage = null;
            this.btnEmployeeRegistration.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeRegistration.OnPressedState.BorderRadius = 20;
            this.btnEmployeeRegistration.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployeeRegistration.OnPressedState.BorderThickness = 1;
            this.btnEmployeeRegistration.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEmployeeRegistration.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEmployeeRegistration.OnPressedState.IconLeftImage = null;
            this.btnEmployeeRegistration.OnPressedState.IconRightImage = null;
            this.btnEmployeeRegistration.Size = new System.Drawing.Size(200, 39);
            this.btnEmployeeRegistration.TabIndex = 5;
            this.btnEmployeeRegistration.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmployeeRegistration.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEmployeeRegistration.TextMarginLeft = 0;
            this.btnEmployeeRegistration.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEmployeeRegistration.UseDefaultRadiusAndThickness = true;
            this.btnEmployeeRegistration.Click += new System.EventHandler(this.btnEmployeeRegistration_Click);
            // 
            // pictureBox2
            // 
            this.pictureBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pictureBox2.Image = global::Employees_Management_System.Properties.Resources.Employees;
            this.pictureBox2.Location = new System.Drawing.Point(0, 0);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(1195, 740);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 13;
            this.pictureBox2.TabStop = false;
            // 
            // Employees
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.btnBlacklist);
            this.Controls.Add(this.btnEmployeeQRCardInfo);
            this.Controls.Add(this.bunifuButton3);
            this.Controls.Add(this.btnEmployeeEditing);
            this.Controls.Add(this.btnEmployeeAccount);
            this.Controls.Add(this.btnEmployeeRegistration);
            this.Controls.Add(this.pictureBox2);
            this.Name = "Employees";
            this.Size = new System.Drawing.Size(1195, 740);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEmployeeRegistration;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEmployeeAccount;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEmployeeEditing;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEmployeeQRCardInfo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBlacklist;
        private System.Windows.Forms.PictureBox pictureBox2;
    }
}
